/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Claim {
    id: string;
    itemId: string;
    contact: string;
    clue1: string;
    clue2: string;
    clue3: string;
    name: string;
    timestamp: Time;
}
export type Time = bigint;
export interface Item {
    id: string;
    status: Status;
    title: string;
    contact: string;
    description: string;
    timestamp: Time;
    itemType: ItemType;
    category: Category;
    location: string;
}
export interface Finder {
    contact: string;
    totalReturned: bigint;
    name: string;
    creditScore: bigint;
}
export enum Category {
    documents = "documents",
    clothing = "clothing",
    pets = "pets",
    jewelry = "jewelry",
    others = "others",
    electronics = "electronics"
}
export enum ItemType {
    found = "found",
    lost = "lost"
}
export enum Status {
    resolved = "resolved",
    active = "active",
    claim_pending = "claim_pending"
}
export interface backendInterface {
    addItem(id: string, title: string, description: string, category: Category, location: string, itemType: ItemType, contact: string): Promise<void>;
    approveClaim(claimId: string): Promise<void>;
    getActiveItems(): Promise<Array<Item>>;
    getAllClaims(): Promise<Array<Claim>>;
    getAllItems(): Promise<Array<Item>>;
    getClaimsByItem(itemId: string): Promise<Array<Claim>>;
    getFinders(): Promise<Array<Finder>>;
    getItemsWithFinder(): Promise<Array<Item>>;
    rejectClaim(claimId: string): Promise<void>;
    resolveItem(id: string): Promise<void>;
    submitClaim(itemId: string, name: string, contact: string, clue1: string, clue2: string, clue3: string): Promise<void>;
}
import type { Category as _Category, Item as _Item, ItemType as _ItemType, Status as _Status, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addItem(arg0: string, arg1: string, arg2: string, arg3: Category, arg4: string, arg5: ItemType, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addItem(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_ItemType_n3(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItem(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_ItemType_n3(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async approveClaim(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveClaim(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveClaim(arg0);
            return result;
        }
    }
    async getActiveItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveItems();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveItems();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllClaims(): Promise<Array<Claim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClaims();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClaims();
            return result;
        }
    }
    async getAllItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllItems();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllItems();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClaimsByItem(arg0: string): Promise<Array<Claim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClaimsByItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClaimsByItem(arg0);
            return result;
        }
    }
    async getFinders(): Promise<Array<Finder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinders();
            return result;
        }
    }
    async getItemsWithFinder(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemsWithFinder();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemsWithFinder();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectClaim(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectClaim(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectClaim(arg0);
            return result;
        }
    }
    async resolveItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveItem(arg0);
            return result;
        }
    }
    async submitClaim(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitClaim(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitClaim(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_Category_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ItemType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemType): ItemType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Item_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Item): Item {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    title: string;
    contact: string;
    description: string;
    timestamp: _Time;
    itemType: _ItemType;
    category: _Category;
    location: string;
}): {
    id: string;
    status: Status;
    title: string;
    contact: string;
    description: string;
    timestamp: Time;
    itemType: ItemType;
    category: Category;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n8(_uploadFile, _downloadFile, value.status),
        title: value.title,
        contact: value.contact,
        description: value.description,
        timestamp: value.timestamp,
        itemType: from_candid_ItemType_n10(_uploadFile, _downloadFile, value.itemType),
        category: from_candid_Category_n12(_uploadFile, _downloadFile, value.category),
        location: value.location
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    found: null;
} | {
    lost: null;
}): ItemType {
    return "found" in value ? ItemType.found : "lost" in value ? ItemType.lost : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    documents: null;
} | {
    clothing: null;
} | {
    pets: null;
} | {
    jewelry: null;
} | {
    others: null;
} | {
    electronics: null;
}): Category {
    return "documents" in value ? Category.documents : "clothing" in value ? Category.clothing : "pets" in value ? Category.pets : "jewelry" in value ? Category.jewelry : "others" in value ? Category.others : "electronics" in value ? Category.electronics : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    active: null;
} | {
    claim_pending: null;
}): Status {
    return "resolved" in value ? Status.resolved : "active" in value ? Status.active : "claim_pending" in value ? Status.claim_pending : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Item>): Array<Item> {
    return value.map((x)=>from_candid_Item_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ItemType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): _ItemType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    documents: null;
} | {
    clothing: null;
} | {
    pets: null;
} | {
    jewelry: null;
} | {
    others: null;
} | {
    electronics: null;
} {
    return value == Category.documents ? {
        documents: null
    } : value == Category.clothing ? {
        clothing: null
    } : value == Category.pets ? {
        pets: null
    } : value == Category.jewelry ? {
        jewelry: null
    } : value == Category.others ? {
        others: null
    } : value == Category.electronics ? {
        electronics: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): {
    found: null;
} | {
    lost: null;
} {
    return value == ItemType.found ? {
        found: null
    } : value == ItemType.lost ? {
        lost: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
