/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'documents' : IDL.Null,
  'clothing' : IDL.Null,
  'pets' : IDL.Null,
  'jewelry' : IDL.Null,
  'others' : IDL.Null,
  'electronics' : IDL.Null,
});
export const ItemType = IDL.Variant({ 'found' : IDL.Null, 'lost' : IDL.Null });
export const Status = IDL.Variant({
  'resolved' : IDL.Null,
  'active' : IDL.Null,
  'claim_pending' : IDL.Null,
});
export const Time = IDL.Int;
export const Item = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'title' : IDL.Text,
  'contact' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'itemType' : ItemType,
  'category' : Category,
  'location' : IDL.Text,
});
export const Claim = IDL.Record({
  'id' : IDL.Text,
  'itemId' : IDL.Text,
  'contact' : IDL.Text,
  'clue1' : IDL.Text,
  'clue2' : IDL.Text,
  'clue3' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : Time,
});
export const Finder = IDL.Record({
  'contact' : IDL.Text,
  'totalReturned' : IDL.Nat,
  'name' : IDL.Text,
  'creditScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Category, IDL.Text, ItemType, IDL.Text],
      [],
      [],
    ),
  'approveClaim' : IDL.Func([IDL.Text], [], []),
  'getActiveItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getAllClaims' : IDL.Func([], [IDL.Vec(Claim)], ['query']),
  'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getClaimsByItem' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
  'getFinders' : IDL.Func([], [IDL.Vec(Finder)], ['query']),
  'getItemsWithFinder' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'rejectClaim' : IDL.Func([IDL.Text], [], []),
  'resolveItem' : IDL.Func([IDL.Text], [], []),
  'submitClaim' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'documents' : IDL.Null,
    'clothing' : IDL.Null,
    'pets' : IDL.Null,
    'jewelry' : IDL.Null,
    'others' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const ItemType = IDL.Variant({ 'found' : IDL.Null, 'lost' : IDL.Null });
  const Status = IDL.Variant({
    'resolved' : IDL.Null,
    'active' : IDL.Null,
    'claim_pending' : IDL.Null,
  });
  const Time = IDL.Int;
  const Item = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'title' : IDL.Text,
    'contact' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'itemType' : ItemType,
    'category' : Category,
    'location' : IDL.Text,
  });
  const Claim = IDL.Record({
    'id' : IDL.Text,
    'itemId' : IDL.Text,
    'contact' : IDL.Text,
    'clue1' : IDL.Text,
    'clue2' : IDL.Text,
    'clue3' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : Time,
  });
  const Finder = IDL.Record({
    'contact' : IDL.Text,
    'totalReturned' : IDL.Nat,
    'name' : IDL.Text,
    'creditScore' : IDL.Nat,
  });
  
  return IDL.Service({
    'addItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Category, IDL.Text, ItemType, IDL.Text],
        [],
        [],
      ),
    'approveClaim' : IDL.Func([IDL.Text], [], []),
    'getActiveItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getAllClaims' : IDL.Func([], [IDL.Vec(Claim)], ['query']),
    'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getClaimsByItem' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
    'getFinders' : IDL.Func([], [IDL.Vec(Finder)], ['query']),
    'getItemsWithFinder' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'rejectClaim' : IDL.Func([IDL.Text], [], []),
    'resolveItem' : IDL.Func([IDL.Text], [], []),
    'submitClaim' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };