/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'documents' : null } |
  { 'clothing' : null } |
  { 'pets' : null } |
  { 'jewelry' : null } |
  { 'others' : null } |
  { 'electronics' : null };
export interface Claim {
  'id' : string,
  'itemId' : string,
  'contact' : string,
  'clue1' : string,
  'clue2' : string,
  'clue3' : string,
  'name' : string,
  'timestamp' : Time,
}
export interface Finder {
  'contact' : string,
  'totalReturned' : bigint,
  'name' : string,
  'creditScore' : bigint,
}
export interface Item {
  'id' : string,
  'status' : Status,
  'title' : string,
  'contact' : string,
  'description' : string,
  'timestamp' : Time,
  'itemType' : ItemType,
  'category' : Category,
  'location' : string,
}
export type ItemType = { 'found' : null } |
  { 'lost' : null };
export type Status = { 'resolved' : null } |
  { 'active' : null } |
  { 'claim_pending' : null };
export type Time = bigint;
export interface _SERVICE {
  'addItem' : ActorMethod<
    [string, string, string, Category, string, ItemType, string],
    undefined
  >,
  'approveClaim' : ActorMethod<[string], undefined>,
  'getActiveItems' : ActorMethod<[], Array<Item>>,
  'getAllClaims' : ActorMethod<[], Array<Claim>>,
  'getAllItems' : ActorMethod<[], Array<Item>>,
  'getClaimsByItem' : ActorMethod<[string], Array<Claim>>,
  'getFinders' : ActorMethod<[], Array<Finder>>,
  'getItemsWithFinder' : ActorMethod<[], Array<Item>>,
  'rejectClaim' : ActorMethod<[string], undefined>,
  'resolveItem' : ActorMethod<[string], undefined>,
  'submitClaim' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];